name: Update Repo from Rocker_Versions2

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    timeout-minutes: 15
#    container:
#      image: rocker/tidyverse:latest
    steps:
      - name: checkout this repo
        uses: actions/checkout@v6
      - name: copy from the rocker_versiond 2 repo
        uses: actions/checkout@v6
        with:
          repository: rocker-org/rocker-versioned2
          path: './rocker'
      - name: copy files across
        run: |
          cp -rp rocker/.github/workflows/* ./.github/workflows_original
          cp -p rocker/Makefile  ./Makefile
          cp -rp rocker/scripts/*  ./scripts
          cp  rocker/build/README.md ./build
          cp  rocker/build/knit-report.R ./build
          cp rocker/build/reports/_Sidebar.md ./build/reports
          cp rocker/build/reports/template.Rmd ./build/reports
          cp rocker/build/reports/versions.Rmd ./build/reports/versions-master.Rmd
          cp rocker/build/reports/wiki_home.Rmd ./build/reports
          cp  rocker/build/scripts/clean-files.R ./build/scripts/clean-files.R
          cp  rocker/build/scripts/generate-args.R ./build/scripts/generate-args-master.R
          cp  rocker/build/scripts/generate-bakefiles.R ./build/scripts/generate-bakefiles-master.R
          cp  rocker/build/scripts/generate-dockerfiles.R ./build/scripts/generate-dockerfiles-master.R
          cp  rocker/build/scripts/generate-matrix.R ./build/scripts/generate-matrix.R
          cp  rocker/build/scripts/generate-variables.R ./build/scripts/generate-variables-master.R
          cp rocker/build/templates/bakefiles/main.docker-bake.json ./build/templates/bakefiles/main.docker-bake-master.json
          cp rocker/build/templates/bakefiles/experimental.docker-bake.json ./build/templates/bakefiles/experimental.docker-bake.json
          cp -rp rocker/tests/* ./tests

#          cp -r rocker/build/templates/dockerfiles/* ./build/templates/dockerfiles
      - name: Set as safe for following git commands
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
  #    - name: install packages
  #      run: |
  #        install2.r --error --skipinstalled -n -1 pak

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.WORKFLOW }}
          commit-message: Automatic update of repo copy and edit
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          signoff: false
          branch: auto-detected-repo-updates
          delete-branch: true
          title: 'Automatic update or repository'
          body: |
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          draft: false
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
